var num1 = 15;
var num2 = 17;
console.log("\nValue of num1 : " + num1);
console.log("\nValue of num2 : " + num2);
var result = num1 > num2;
console.log("\n" + num1 + " is greater than " + num2 + " : " + result);
result = num1 < num2;
console.log("\n" + num1 + " is lesser than " + num2 + " : " + result);
result = num1 >= num2;
console.log("\n" + num1 + " is greater than or equal to " + num2 + " : " + result);
result = num1 <= num2;
console.log("\n" + num1 + " is lesser than or equal to " + num2 + " : " + result);
result = num1 == num2;
console.log("\n" + num1 + " is equal to " + num2 + " : " + result);
result = num1 != num2;
console.log("\n" + num1 + " is not equal to " + num2 + " : " + result);
